publichealthengland/ntbs-reporting

.gitignore
README.md
source/ntbs-reporting.sqlproj

Update the README, add support for a per-developer publishing script in the `.sqlproj` file, and ignore this script in source control.
No formal testing required, though this is based on me going through the process of setting up a new reporting database with Nancy.

NTBS-NONE Use per-developer databases

---

source/dbo/Stored Procedures/Reusable Notification/uspGenerateReusableNotification.sql
source/dbo/Stored Procedures/Reusable Notification/uspGenerateReusableNotificationTreatmentRegimen_ETS.sql
source/dbo/Tables/Reusable Notification/TreatmentRegimenLookup.sql
source/dbo/uspSeed.sql
source/ntbs-reporting.sqlproj

A change missed from #19 review before it was merged into `master`.
Use textual descriptions `('Standard treatment', 'RR/MDR/XDR treatment', 'Other')` instead of codes `('StandardTreatment', 'MdrTreatment', 'Other')` in the new `ReusableNotification.TreatmentRegimen` column.
Add a `TreatmentRegimen` lookup table to convert between the two formats.
Published to my Azure dev database, results the same as last time just now encoded correctly. This has not been deployed to any other DB.

NTBS-1664 Use treatment regimen descriptions, not codes

---

source/dbo/Stored Procedures/Reusable Notification/uspGenerateReusableNotificationTreatmentRegimen_ETS.sql

When checking whether an ETS planned treatment is not equal to 1 (eg. `ShortCourseTreatment <> 1`), this condition also needs to return return if the value is `NULL`. Do this using `COALESCE` expressions.
Tested on my Azure dev DB, found examples of this issue (eg. `EtsId = 142466`) and checked they no longer are present after the change. I've not deployed this anywhere else.

NTBS-1664 Check for nulls when setting treatment regimen

---

source/dbo/Stored Procedures/Reusable Notification/uspGenerateReusableNotification.sql
source/dbo/Tables/Reusable Notification/ReusableNotification.sql

Added Lat, Long and ClusterId to reusable notification. Adding these meant that references to clusterId no longer need to be gotten from joins, so to be able to build this (without ambiguous reference errors) I removed those joins.

NTBS-2179: Add columns to reusable notification

---

README.md
source/Scripts/PopulateFeatureFlags.sql
source/dbo/uspSeed.sql
source/ntbs-reporting.sqlproj

* Update README: NTBS-2188 specimen matching changes in publichealthengland/ntbs-specimen-matching#5
* Run `uspPopulateCalendarTable` from `uspSeed` (but only do this during its first run)
* Run code based on `PopulateFeatureFlags.sql` script during initial DB setup from `uspSeed`
* Remove `PopulateFeatureFlags.sql` because it has been inlined into `uspSeed`
This means the entire DB can be set up just by running `uspGenerate`.
Tested both acceptance criteria on local DBs: that the calendar table and feature flags are not modified if there already exists records in those tables, and that I can create a new reporting DB and it successfully runs `uspGenerate`, populating the calendar and feature flag tables.

NTBS-2188 Improve uspSeed

---

source/dbo/Stored Procedures/Data Migration/uspConfirmationLineList.sql
source/dbo/Stored Procedures/Data Migration/uspMigrationAdditionalNotificationsByRegionAndYear.sql
source/dbo/Stored Procedures/Data Migration/uspMigrationLineList.sql
source/dbo/Stored Procedures/Data Migration/uspMigrationSelectedNotificationsByYear.sql

Now only take records from the last 3 full years and also exclude any records that are already migrated into NTBS.

NTBS-1824: Take account of migrated records and update date on migration reports

---

README.md

QA addition: Document known issues with running `uspGenerate` in specimen-matching, related to having small amounts of data.

NTBS-2231 Add known specimen matching issues to README

---

source/dbo/Stored Procedures/Extracts/uspPopulateForestExtract.sql

Some fixes that came back from QA. Mainly just mapping 1/0's to Yes/No or Yes/blank.
Also I'd joined the residence phec on the wrong field, which has now been fixed and is populating properly.

NTBS-2261: Fix fields in population of forest extract

---

source/dbo/Stored Procedures/Power BI Reporting/uspGenerateEtsCaseRecord.sql
source/dbo/Stored Procedures/Power BI Reporting/uspGenerateNtbsCaseRecord.sql
source/dbo/Tables/Power BI Reporting/Record_CaseData.sql

Add a comma separated list of disease sites to `Record_Data.DiseaseSiteList`, a new field. This comes from NTBS and ETS
depending on the notification, and uses disease site names from the respective system.
This is based on how a similar field is calculated for `ForestExtract`. 
Tested the insertion locally using the basic test data, and have tested the queries work on live data (just not the insertion bit). This code has not been deployed anywhere

NTBS-2302 Add disease site list to Record_CaseData

---

source/dbo/Stored Procedures/Power BI Reporting/uspGenerateReportingCaseData.sql
source/dbo/Stored Procedures/Power BI Reporting/uspMapCaseRecordChestXrayResults.sql

Add the 'No result' value to ETS records chest xray result.

NTBS-2259: Add default no result value for chest xray for all case record

---

source/dbo/Functions/Reusable Notification/ufnGetTreatmentOutcome.sql

When a patient has not completed a full course and there is no further
reason, the summary should be "Not evaluated" rather than "Lost to
follow-up".
I've not managed to test this locally but given how straightforward the change is I'm pretty confident it will work. It builds and deploys locally ok

NTBS-2317 Fix a treatment event mapping in migration report

---

source/dbo/Stored Procedures/Lab Results/uspAllEtsMatches.sql
source/dbo/Stored Procedures/Lab Results/uspNewEtsMatches.sql
source/dbo/Stored Procedures/Lab Results/uspRecentSpecimensByRefLab.sql
source/dbo/Stored Procedures/Lab Results/uspSummaryUnmatchedLabSpecimens.sql
source/dbo/Views/Reusable Drop Downs/vwNotificationYear.sql
source/ntbs-reporting.sqlproj
sql-clients/ssrs/Data Migration/Confirm Users and Services.rdl
sql-clients/ssrs/Data Migration/Migration List Confirmation.rdl
sql-clients/ssrs/Data Migration/Migration List.rdl
sql-clients/ssrs/Data Migration/Migration Results.rdl
sql-clients/ssrs/Data Migration/SOP Specimen Match Multi System.rdl
sql-clients/ssrs/Data Migration/Subreport/User_subreport.rdl

Made updates to the migration reports so that:
* they can run against the EtsSpecimenMatch table in the specimen matching database, instead of in the reporting database
* they are properly parameterised, so we can deploy these against the live and UAT instances as well as dev (this partly involved moving queries out of SSRS and into stored procedures, which is why the code appears new)
* the reporting period is finally set correctly back to current year + 3 previous, not +4 previous, which is a hangover to a long-ago change made for the East of England region
I have also removed some dependencies on a table called 'TB Service short names' which I used to populate the sheet names on a report which was intended for extract to Excel.  The table has gone; I must never have committed it to …

NTBS-2239 and NTBS-2290

---

source/Publish Profiles/Pre-production/phe-ntbs-dev-reporting.publish.xml

Rename the NTBS DB used by `phe-dev`, 'NTBS_Live' to 'NTBS_Dev'
This change has already been deployed

NTBS-2351 Rename phe-dev NTBS DB

---

source/Publish Profiles/DELETE/phe-ntbs-uat-reporting-DELETE.publish.xml
source/Publish Profiles/Pre-production/phe-ntbs-uat-reporting.publish.xml

Use the PHE UAT migration DB that has recently been created instead of the live one for UAT reporting,
This has not been deployed anywhere

NTBS-2358 Use PHE UAT migration DB instead of live

---

source/dbo/Stored Procedures/Extracts/uspPopulateForestExtract.sql
source/dbo/Stored Procedures/Power BI Reporting/uspGenerateNtbsCaseRecord.sql

Fix records without chest x-rays getting missed by the Record_CaseData
and ForestExtract generating procedures.
This was an issue because ufnGetCaseRecordChestXrayResults returns
nothing if the notification doesn't have a chest X-Ray, so the
notification gets discarded by a cross apply, but not an outer apply.
Tested (more thoroughly this time!) on local data. This has not been deployed anywhere

NTBS-2355 Fix records without X-rays getting ignored

---

source/dbo/Stored Procedures/Power BI Reporting/uspGenerateReportingLegacySitesOfDisease.sql

Add the `SiteDescription` text stored for 'other' disease sites in NTBS to the legacy extract.
Tested locally using ETS test data. This change has not been deployed anywhere yet.

NTBS-2414 Add other disease site text to legacy extract

---

source/dbo/Stored Procedures/Power BI Reporting/uspGenerateReportingRecords.sql
source/dbo/Stored Procedures/Power BI Reporting/uspUpdateRecordPostcode.sql

When populating `Record_PersonalDetails.Postcode`, first set this to the NTBS `Patients.Postcode`. This is what the user entered, and may be invalid, and may not be formatted correctly.
Replace `Record_PersonalDetails.Postcode` with a formatted version of `Patients.PostcodeToLookup`, if it exists and is valid. If it doesn't exist or is invalid, leave `Record_PersonalDetails.Postcode` as what the user originally entered.
Tested locally with an amended version of ETS to have BPFO postcodes. This has not been deployed anywhere

NTBS-2389 Keep Record_PersonalDetails.Postcode when invalid

---

source/dbo/Stored Procedures/Power BI Reporting/uspGenerateReportingLegacyExtract.sql

In our general reporting world, we have a field called 'Sample Taken' rather than the value which has always been used historically, 'No Sample Taken'. For the Legacy Extract, we thus need to create a reverse value.
We also noted during testing that if World Region is empty, the Legacy Extract outputs 'Unknown' in ETS so have reproduced that as well.

NTBS-2432: No Sample taken

---

source/dbo/Stored Procedures/Data Migration/uspGenerateMigrationResultsData.sql

Migration run ID of 6 had been left in the code, should be variable @MigrationRunID

Removed hard-coded Migration Run ID

---

source/dbo/uspSeed.sql

This is to make the text read better when the Power BI version is added to it during the load to Power BI.  When displayed, the text should now read: 
`Reporting database version: Release-<number>-<date> Power BI Version: Release-<number>-<date>`

NTBS-2469 - updated text of footer

---

source/dbo/Views/Power BI Reporting/vwNOIDSExtract.sql
source/ntbs-reporting.sqlproj

This is an initial version of the NOIDS extract view.  I have created it as a view because it will effectively be materialised when it is pushed to Power BI.  
The rules for the Specificity_Code field still need to be validated with the national team.
There is also some substitution of Local Authority names which may require another mapping statement in the CTE, to be confirmed tomorrow.

NTBS-2502 initial code

---

source/dbo/Views/Power BI Reporting/vwUnmatchedDuplicates.sql
source/ntbs-reporting.sqlproj

Add a report for use in PowerBi for basic duplicate identification across NTBS and ETS, for records with identical NHS numbers and dates of birth
View query tested on PHE dev using live data. It takes a couple of seconds to run (but will be materialised in a PowerBi report table eventually so this is no issue)

NTBS-2500 Add unmatched duplicate report view

---

source/dbo/Views/Power BI Reporting/vwUnmatchedDuplicates.sql

Ignore NHS numbers like 'NK' when trying to find duplicate NHS numbers across notifications.
Tested query from view on UAT data, and invalid string NHS numbers are now excluded. This has not been deployed anywhere yet.

NTBS-2500 Don't use string NHS numbers to finding duplicates

---

source/dbo/Stored Procedures/Data Migration/uspGenerateMigrationResultsData.sql

This did not work when we first ran it in live, because it first looks at its own table, MigrationRun, to see what is the last job number it processed. If it doesn't find one (as it would not on first execution in an environment) it looks for one with a value greater than 1. It should be zero; the first migration run has the number 1.

Update to logic which looks for the migration job to process from NTBS

---

source/dbo/Stored Procedures/Lab Results/uspSummarisedNTBSMatches.sql

The possible matches were not being included in the count, because their matchmethod is NULL so were excluded by the WHERE clause

NTBS-2547: Bug fix

---

source/dbo/Views/Power BI Reporting/vwCaseManagerIssuesReport.sql
source/dbo/Views/Power BI Reporting/vwRegionAndPermissions.sql

Changed case on field names as the build warnings create noise during the release process

NTBS-2574: remove build warnings

---

source/dbo/Views/Power BI Reporting/vwLegacyLabExtract.sql
source/ntbs-reporting.sqlproj

This view pulls together data on manual and reference lab results for both ETS and NTBS.  There are some additional columns in the final report (things like TreatmentRegion) but these items are already available in Power BI so I will add them on to the dataset there.
I've tested this against live data and it looks basically correct, but following deployment to phe-dev we will do a manual comparison with the one produced by ETS. This will not be identical, as the ETS one misses out WGS lab results, but will tell us if we've got it right.

Initial code for legacy lab extract

---

source/dbo/Stored Procedures/Data Migration/uspGenerateMigrationResultsData.sql

In the migration run report, when a notification does not have any log messages, get the migration notes from the outcome instead.
I've tested this against a small migration run, including one notification which fails to import because a linked notification fails validation.

NTBS-2489 Include notes from migration run outcomes without log messages

---

source/dbo/Stored Procedures/Reusable Footer/uspGenerateFooter.sql

The code had not been updated after the audit database was restructured, so it was looking in the 'EntityType' column for the value 'Notification' when it should be looking in the 'RootEntity' column.  This is having a minor effect in live, depending on what kind of updates are performed the day before.

NTBS-2588 incorrect date appears in report footer for NTBS

---

source/dbo/Stored Procedures/Data Migration/uspMigrationDuplicateAlerts.sql
source/dbo/Stored Procedures/Data Migration/uspMigrationSpecimenMatchesToReviewBySpecimen.sql
sql-clients/ssrs/Data Migration/Migration Results.rdl

Adding some extra data to the procedures which are used in the migration run reports. 
Added ETS ID and 'Demographics match' of the duplicate notification in the case of a duplicate alert - and made it so that it only outputs one row per duplicate.
Made the dubious specimen match return all the notifications which were part of the dubious match, not only the notification which was part of the migration. Also returned the status of the notifications in ETS. 
The only changes to the actual report are: Adding in the extra fields and now grouping the specimens by reference lab number instead of by notification

NTBS-2659: Improve migration results report

---

source/dbo/Stored Procedures/Data Migration/uspMigrationDuplicateAlerts.sql
source/dbo/Stored Procedures/Data Migration/uspMigrationSpecimenMatchesToReviewBySpecimen.sql

I hadn't thought about the fact that MigrationRunResults will have all the old runs in, so was joining all cases of a notification. Now join on the MigrationRunId also.

NTBS-2659: Fix migration report stored procs

---

source/dbo/uspSeed.sql

Remove the word "database" from the reporting footer. I have also updated the identifiable dataset pbix as part of this ticket to no longer add the Power BI reporting version to the footer. That change is on the NTBS reports on azure

NTBS-2677: Edit report footer text

---

source/dbo/Stored Procedures/Power BI Reporting/uspGenerateReportingCaseData.sql
source/dbo/Stored Procedures/Power BI Reporting/uspGenerateSputumResult.sql
source/dbo/Tables/Power BI Reporting/Record_CaseData.sql
source/ntbs-reporting.sqlproj
sql-clients/ssrs/Data Migration/Migration Results.rdl

Sputum testing is normally done for all pulmonary cases and in some regions it is a KPI which is reviewed at cohort review. We have been asked to add a field to the NTBS [enhanced] line list that summarises the results of all sputum tests for the case.
There is an outstanding question about whether this should exclude culture results (probably) or line probe assay (probably not).  Hence the TODO comments and commented out line in the code.  If we don't hear from the Yorkshire team tomorrow, I will leave it as written and we can hot fix a change if required.
I can't really develop the Power BI report change until I can merge the SQL in.

NTBS-2700: summarise results of sputum testing

---

source/dbo/Stored Procedures/Power BI Reporting/uspGenerateEtsCaseRecord.sql

Changed ETS case record to set started treatment to yes if treatment start date populated.
Not needed for the NTBS case records, as we only allow the input of a date if they have set Started treatment to Yes.

NTBS-2647: Set started treatment to yes if treatment start date populated

---

source/dbo/Stored Procedures/Power BI Reporting/uspGenerateNtbsCaseRecord.sql
source/dbo/Stored Procedures/Power BI Reporting/uspGenerateSputumResult.sql
source/dbo/Views/Power BI Reporting/vwLegacyLabExtract.sql

Also I found a bug, where we hadn't added excluded chest CTs from the legacy lab extract.
Nothing in GenerateCaseData needs to be changed, as we coalesce on "No result", and our query will not pick up "NoResult" (the new result) results. So these will end up as "No result" which is the desired outcome.

NTBS-2813: Add no result test result

---

source/Publish Profiles/Pre-production/azure-int-reporting.publish.xml
source/Publish Profiles/Pre-production/azure-test-reporting.publish.xml
source/Publish Profiles/Pre-production/phe-dev-reporting.publish.xml
source/Publish Profiles/Pre-production/phe-uat-reporting.publish.xml
source/Publish Profiles/Production/phe-live-reporting.publish.xml
source/dbo/Views/Reusable Drop Downs/vwNotificationYear.sql
source/ntbs-reporting.sqlproj

Allow us to set the number of reporting years of data in the publish profile, so that we can change it on a per-environment basis

NTBS-2987 Add SQL CMD variable for number of reporting years

---

source/dbo/Views/Power BI Reporting/vwServiceDirectory.sql
source/ntbs-reporting.sqlproj

The service directory report will display information about regions and their staff + TB services and their staff, including contact details.  New view to expose the right data to Power BI.
It doesn't include the national team because their individual contact details have never been included in the service directory. I have put in a clause to exclude Softwire staff from being displayed because @JoshCadney has a London regional role which is really useful for testing but we don't want him to appear in the service directory.

NTBS-1526: initial view for service directory report

---

source/dbo/Functions/Reusable Notification/ufnGetPeriodicOutcome.sql
source/dbo/Functions/Reusable Notification/ufnGetServiceResponsible.sql
source/dbo/Stored Procedures/Power BI Reporting/uspGenerateRecordOutcome.sql
source/dbo/Stored Procedures/SSRS Reporting/uspGenerateReusableOutcomePeriodic.sql
source/dbo/Tables/Reusable Notification/AllTransfers.sql
source/dbo/Tables/Reusable Notification/Outcome.sql
source/dbo/Tables/Reusable Notification/TransfersOut.sql
source/ntbs-reporting.sqlproj

Only generate a "service responsible at X months" if there is an outcome at X months (for 24 and 36, 12 is always calculated).
Brought the logic into it's own function.
Fixed the case where there is a transfer on the day of the outcome.

NTBS-2944: Fix service responsible fields in case data

---

source/dbo/Stored Procedures/SSRS Reporting/uspUpdateOutcomesForPostMortemCases.sql

I realised when testing NTBS-2973 that the correct outcome for post-mortem cases is being set after `[uspGenerateReusableOutcomePeriodic]` is called for period 1, meaning the new 'descriptive' outcome fields are not set to the right value for post-mortem cases.
I added the logic used to return both the short and long outcome descriptions into` [uspUpdateOutcomesForPostMortemCases]`. It reproduces some of the logic in `ufnGetPeriodicOutcome` but I think it's the best way to handle it, given we make a special case for post-mortem case outcomes anyway.

NTBS-2997 - add descriptive outcome for post-mortem cases

---

source/dbo/Functions/Reusable Notification/ufnGetPeriodicOutcome.sql

Treatment outcome 14 is the only outcome that has a NULL in the subtype column, this wasn't playing nicely with `<>` so it wasn't being seen as an ending outcome. Switching to an equality check has solved that

NTBS-3010: Deal with null in subtype of outcome

---

source/dbo/Views/Power BI Reporting/vwMissingCohortReviewItems.sql

To prevent every notification appearing on the missing items report, it has been decided that notifications should only show as missing 'referral received' if the notification is from 2022 or later.

NTBS-3028 add notification to missing item report if referral date empty only for records after 2022

---

source/dbo/Stored Procedures/Power BI Reporting/uspGenerateInitialSputumResults.sql
source/dbo/Stored Procedures/Power BI Reporting/uspGenerateNtbsCaseRecord.sql
source/dbo/Stored Procedures/Power BI Reporting/uspGenerateReportingCaseData.sql
source/dbo/Stored Procedures/Power BI Reporting/uspGenerateSputumResult.sql
source/dbo/Stored Procedures/Power BI Reporting/uspGenerateTestResultSummaries.sql
source/dbo/Stored Procedures/Power BI Reporting/uspPopulateLookupTables.sql
source/dbo/Tables/Power BI Reporting/ManualTestResultRanking.sql
source/ntbs-reporting.sqlproj

Made the ranking a lookup table, as it is used in a few different places. 
Made the logic for all the different test result summaries consistent (with how we do it for the `Initial...` fields)

NTBS-3071: Make test result summaries consistent

---

source/dbo/Stored Procedures/Data Migration/uspMigrationDuplicateAlerts.sql

Fix the data quality alert for a potential duplicate being misspelled as “DataQualityPotientialDuplicate”.
There is also a PR for the ntbs_Beta repo with the application changes.

NTBS-3094 fix spelling error for data quality alert
