publichealthengland/ntbs-reporting

source/dbo/Stored Procedures/Power BI Reporting/uspMapCaseRecordChestXrayResults.sql

Added a default value for no chest x-ray result.

NTBS-2259: Add default value for no chest xray result

---

source/dbo/Functions/Power BI Reporting/ufnGetEtsBirthCountryAsNtbsCountry.sql
source/dbo/Stored Procedures/Power BI Reporting/uspGenerateEtsCaseRecord.sql
source/ntbs-reporting.sqlproj

Extract ETS countries of birth using its ID and also whether the patient is marked as `UkBorn`, and map the extracted country code to an NTBS-style mixed-case name.
Tested using some ETS records I manipulated locally. This has not been deployed anywhere

NTBS-2275 Map ETS birth countries to NTBS in Record_CaseData

---

source/dbo/Stored Procedures/Power BI Reporting/uspGenerateReportingRecords.sql
source/dbo/Stored Procedures/Power BI Reporting/uspUpdateRecordNhsNumber.sql
source/dbo/Tables/Power BI Reporting/Record_PersonalDetails.sql
source/ntbs-reporting.sqlproj

We want a formatted NHS number in both columns:
- In the NhsNumber column we want 000 000 0000 
- In the NhsNumberToLookup column we want 0000000000
Unless the NHS number has alphabetic characters, in which case we want NhsNumber to be unchanged.

NTBS-2273: Add new column with formatted nhs number to record patient details

---

source/dbo/Stored Procedures/Power BI Reporting/uspGenerateEtsCaseRecord.sql
source/dbo/Stored Procedures/Power BI Reporting/uspGenerateReportingLegacyExtract.sql
source/dbo/Tables/Power BI Reporting/Record_LegacyExtract.sql

Unclear really why these have appeared now but after newly migrating the data from South West, North East and Wales, and then running uspGenerate in the reporting database, a number of new errors have appeared

NTBS-2321: conversion issues uncovered in reporting code

---

source/dbo/Stored Procedures/Power BI Reporting/uspGenerateReportingLegacySitesOfDisease.sql

Just a minor review markup from #67 refactoring `uspGenerateReportingLegacySitesOfDisease`

NTBS-2414 Minor refactor of legacy disease site mapping

---

source/dbo/Stored Procedures/Power BI Reporting/uspGenerateReportingLegacyPeriodicTOMFields.sql

Add lost to follow-up to `TOMCompletedCourse` in `LegacyExtract`
Tested locally, not deployed anywhere

NTBS-2420 Add lost to follow-up to TOMCompletedCourse

---

source/Publish Profiles/Pre-production/azure-uat-reporting.publish.xml

Add new UAT migration DB to deploy script.
As with the change to migration, what branch should I be looking to merge this into? Maybe `master` to then merge into `future-work`?

NTBS-2419 Add Azure UAT migration DB

---

source/dbo/Views/Power BI Reporting/vwAlert.sql
source/dbo/Views/Power BI Reporting/vwAuditData.sql
source/dbo/Views/Power BI Reporting/vwHangfireJobs.sql
source/ntbs-reporting.sqlproj

Screenshot of dashboard available on Jira ticket.
This lets us monitor activity in NTBS:
- notifications created & on demand data migrations done
- alerts created and closed
- how the Hangfire jobs did last night/last time
- user logins, user edits, record reads
- specimens unmatched

Initial views for a monitoring dashboard

---

source/dbo/Views/Power BI Reporting/vwNotifications.sql
source/ntbs-reporting.sqlproj

Additional view missed from report

Additional view needed for report

---

source/dbo/Views/Power BI Reporting/vwCaseManagerIssuesReport.sql
source/dbo/Views/Power BI Reporting/vwNtbsUsers.sql
source/ntbs-reporting.sqlproj

Views used by the new PowerBI report I'm making, one for the case manager issues and the other just a view on NTBS users to be used to find duplicate users.
Tested locally, this has not been deployed anywhere yet

NTBS-2532, NTBS-2558 Case manager TbService issues report

---

source/dbo/Stored Procedures/Data Migration/uspGenerateMigrationResultsData.sql

Only include submitted outcomes when working out the ETS outcome in the migration run report.
Order events correctly when working out the NTBS outcome in the migration run report.

NTBS-2543 Only consider submitted outcomes

---

source/dbo/Stored Procedures/Data Migration/uspMigrationDuplicateAlerts.sql
sql-clients/ssrs/Data Migration/Migration Results.rdl

Review markup - add a column for the duplicate notification's TB service

NTBS-2546 Add duplicate TB service to report

---

sql-clients/ssrs/Data Migration/Migration Results.rdl

Updated the rdl file for the migration results report. 
The update consisted of removing some unwanted fields and switching the order of notifications in the duplicate table.

NTBS-2659: Update migration results report

---

source/dbo/Views/Authorization/vwUserPermissions.sql
source/dbo/Views/Power BI Reporting/vwAllTbService.sql
source/dbo/Views/Power BI Reporting/vwPhec.sql

The new TB service report needed a couple of extra columns from these views.

NTBS-2676: Add columns to reporting views needed in report

---

source/dbo/Stored Procedures/Data Migration/uspConfirmDatabaseVersions.sql
source/dbo/Stored Procedures/Data Migration/uspGenerateMigrationResultsData.sql
source/dbo/Tables/Data Migration/MigrationRun.sql
sql-clients/ssrs/Data Migration/Migration Results.rdl

Add the migration version to the migration run table, I'll add the rdl file to this once I edit the report.

NTBS-2589: Add migration version to migration run table

---

source/dbo/Stored Procedures/Power BI Reporting/uspGenerateSputumResult.sql

Should be only smear and PCR, which in ETS equates to Microscopy and Molecular Amplification

NTBS-2700 clarify test types required

---

.github/workflows/build-dacpac.yml

I haven't actually tested this yet, but it's pretty much identical to the migration one, so I'm not expecting any problems

NTBS-2405 Build DACPAC and push to blob store

---

source/dbo/Stored Procedures/Power BI Reporting/uspGenerateEtsCaseRecord.sql
source/dbo/Stored Procedures/Power BI Reporting/uspGenerateNtbsCaseRecord.sql
source/dbo/Tables/Power BI Reporting/DiseaseSiteOrdering.sql
source/dbo/uspSeed.sql
source/ntbs-reporting.sqlproj

Added ordering to the sites of disease in Record_CaseData so it mirrors the ordering on the clinical details page

NTBS-2731: Order disease sites in case records to match NTBS

---

source/dbo/Stored Procedures/Power BI Reporting/uspGenerateNtbsCaseRecord.sql

Add mapping for unknown for the MDR discussed field

NTBS-2788: Map unknown for MDR field

---

source/dbo/Stored Procedures/Power BI Reporting/uspGenerateReportingCaseData.sql

Noticed while I was doing the power BI changes.

NTBS-2788: Add no result coalesce for chest CT

---

source/dbo/Views/Power BI Reporting/vwMissingCohortReviewItems.sql
source/ntbs-reporting.sqlproj

Add new view for missing cohort review items report

NTBS-2765: Add view for missing cohort review items

---

source/dbo/Views/Power BI Reporting/vwMissingCohortReviewItems.sql

The power BI report just joins to the table it already has!

NTBS-2765: Remove unneeded columns from missing items view

---

source/dbo/Views/Reusable Drop Downs/vwNotificationYear.sql

This will ensure 2018 is not dropped at the start of 2022.

Include additional year in reporting

---

source/dbo/Stored Procedures/Power BI Reporting/uspGenerateNtbsCaseRecord.sql
source/dbo/Stored Procedures/Power BI Reporting/uspGenerateRecordOutcome.sql
source/dbo/Tables/Power BI Reporting/Record_CaseData.sql

I also fixed a bug where notifications with no diagnosis made/treatment start event were not having outcomes generated in reporting (this was happening with post mortem cases as some only have death events)

NTBS-2944: Add notifying service and 12/24/36 month responsible clinic

---

source/dbo/Stored Procedures/Power BI Reporting/uspGenerateRecordOutcome.sql
source/dbo/Stored Procedures/SSRS Reporting/uspUpdateOutcomesForPostMortemCases.sql
source/ntbs-reporting.sqlproj

Generate correct outcomes for post mortem cases according to new rules.

NTBS-2973: Generate correct outcome for post mortem cases

---

source/Publish Profiles/Pre-production/DEV-reporting.publish.xml
source/Publish Profiles/Pre-production/azure-int-reporting.publish.xml
source/Publish Profiles/Pre-production/azure-load-test-reporting.publish.xml
source/Publish Profiles/Pre-production/azure-test-reporting.publish.xml
source/Publish Profiles/Pre-production/azure-uat-reporting.publish.xml
source/Publish Profiles/Pre-production/phe-dev-reporting.publish.xml
source/Publish Profiles/Pre-production/phe-uat-reporting.publish.xml
source/Publish Profiles/Production/phe-live-reporting.publish.xml
source/Scripts/PostDeploy.sql
source/Scripts/SetEnvironment.sql
source/dbo/Tables/Power BI Reporting/Environment.sql
source/ntbs-reporting.sqlproj

No need for another variable, just putting the name of the NTBS database into a table so I can get it with Power BI and then map the environment -> notification URL

NTBS-3016: Add post deploy script to add environment to database table

---

source/dbo/Functions/Power BI Reporting/ufnMapYesNoToBooleanText.sql
source/dbo/Stored Procedures/Power BI Reporting/uspGenerateNtbsCaseRecord.sql
source/dbo/Stored Procedures/Power BI Reporting/uspGenerateReportingCaseDataSitesOfDisease.sql
source/dbo/Stored Procedures/Power BI Reporting/uspGenerateReportingLegacySitesOfDisease.sql
source/dbo/Tables/Power BI Reporting/Record_CaseData.sql
source/ntbs-reporting.sqlproj

I've moved the logic to update case data, and then use that to populate the legacy extract (so the logic isn't duplicated, just need to map a few fields together and map Yes/No to TRUE/FALSE)

NTBS-3006: Generate a row in case data for each disease site

---

source/dbo/Views/Power BI Reporting/vwApplicationUsage.sql

Add application usage view for internal dashboard report

NTBS-3042 add application usage view

---

source/ntbs-reporting.sqlproj

NTBS-3042: Add view to project file

---

README.md

Add reference to sharepoint backup of geopgraphy database

NTBS-README add reference to sharepoint backup

---

source/dbo/Views/Power BI Reporting/vwAlert.sql

Added some missing alert types, corrected spelling mistake on Potential and improved descriptions of some alert types

NTBS-3125 improve alert descriptions

---

source/dbo/Views/Power BI Reporting/vwDashboardNotifications.sql
source/ntbs-reporting.sqlproj

Created a view with the derived fields needed for the NTBS Dashboard. This will simplify the Power Query logic and provide better maintainability

NTBS-3125 simplified logic in SQL and remove from Power Query
